
-- Run this in your Supabase SQL Editor to create the necessary tables.

-- PROFILES TABLE
CREATE TABLE IF NOT EXISTS profiles (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(), -- TEXT to support LEGACY- IDs if needed, but preferably UUID
    display_name TEXT NOT NULL DEFAULT 'OPERATOR',
    friend_code TEXT,
    avatar_url TEXT DEFAULT '/assets/merchboy_face.png',
    coins BIGINT DEFAULT 0,
    xp BIGINT DEFAULT 0,
    games_played INTEGER DEFAULT 0,
    high_scores JSONB DEFAULT '{}',
    stats JSONB DEFAULT '{}',
    achievements JSONB DEFAULT '[]',
    inventory JSONB DEFAULT '[]',
    settings JSONB DEFAULT '{}',
    daily_data JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen TIMESTAMPTZ DEFAULT NOW()
);

-- FEED EVENTS TABLE
CREATE TABLE IF NOT EXISTS feed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT,
    message TEXT,
    type TEXT, -- 'win', 'jackpot', 'fail', 'fish', etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE feed_events ENABLE ROW LEVEL SECURITY;

-- Public Access policies
CREATE POLICY "Allow public read access profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Allow public insert access profiles" ON profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access profiles" ON profiles FOR UPDATE USING (true);

CREATE POLICY "Allow public read access feed" ON feed_events FOR SELECT USING (true);
CREATE POLICY "Allow public insert access feed" ON feed_events FOR INSERT WITH CHECK (true);

-- Enable Realtime for Feed
alter publication supabase_realtime add table feed_events;
