
-- 1. Create Tables (If Missing)
CREATE TABLE IF NOT EXISTS profiles (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    display_name TEXT NOT NULL DEFAULT 'OPERATOR',
    friend_code TEXT,
    avatar_url TEXT DEFAULT '/assets/merchboy_face.png',
    coins BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT,
    message TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add Columns (If Table Existed but Columns Missing)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS xp BIGINT DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS games_played INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS high_scores JSONB DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS stats JSONB DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS achievements JSONB DEFAULT '[]';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS inventory JSONB DEFAULT '[]';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS daily_data JSONB DEFAULT '{}';

-- 3. Security Policies (Drop First to Avoid Errors)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE feed_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access profiles" ON profiles;
CREATE POLICY "Allow public read access profiles" ON profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access profiles" ON profiles;
CREATE POLICY "Allow public insert access profiles" ON profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access profiles" ON profiles;
CREATE POLICY "Allow public update access profiles" ON profiles FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public read access feed" ON feed_events;
CREATE POLICY "Allow public read access feed" ON feed_events FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access feed" ON feed_events;
CREATE POLICY "Allow public insert access feed" ON feed_events FOR INSERT WITH CHECK (true);

-- 4. Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table feed_events;
commit;
